spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/anydb
    username: anyuser
    password: anypassword
    
    driverClassName: org.postgresql.Driver  